[toolchain]
channel = "nightly-2025-06-09"
components = [
    "rust-src",
    "rustfmt",
    "clippy",
    "rust-analyzer",
    "llvm-tools-preview",
    "miri",
    "rust-docs",
]
profile = "default"
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "wasm32-unknown-unknown",
]
