apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-main
  namespace: loki-system
  labels:
    app: loki-main
    version: v1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki-main
  template:
    metadata:
      labels:
        app: loki-main
        version: v1.0
    spec:
      containers:
      - name: loki
        image: loki:latest
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 8081
          name: api
        envFrom:
        - configMapRef:
            name: loki-config
        - secretRef:
            name: loki-secrets
        volumeMounts:
        - name: loki-data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "4Gi"
            cpu: "2000m"
            ephemeral-storage: "10Gi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: loki-data
        persistentVolumeClaim:
          claimName: loki-pvc
      restartPolicy: Always
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: loki-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: loki-system
  labels:
    app: loki-main
spec:
  selector:
    app: loki-main
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: api
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loki-hpa
  namespace: loki-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loki-main
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30 