apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.fullname" . }}-secret
  labels:
    {{- include "loki.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" "postgres" .Values.postgresql.auth.postgresPassword (include "loki.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
  redis-url: {{ printf "redis://:%s@%s-redis-master:6379/0" .Values.redis.auth.password (include "loki.fullname" .) | b64enc | quote }}
  openai-api-key: {{ .Values.loki.openaiApiKey | b64enc | quote }}
  anthropic-api-key: {{ .Values.loki.anthropicApiKey | b64enc | quote }}
  github-token: {{ .Values.loki.githubToken | b64enc | quote }}
  x-api-key: {{ .Values.loki.xApiKey | b64enc | quote }}
  x-api-secret: {{ .Values.loki.xApiSecret | b64enc | quote }}
  x-access-token: {{ .Values.loki.xAccessToken | b64enc | quote }}
  x-access-secret: {{ .Values.loki.xAccessSecret | b64enc | quote }} 